# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Validate Python
on:
  pull_request:
    branches:
      - main

jobs:
  python-validation:
    runs-on: ubuntu-20.04
    env:
      ENV: test
    steps:
    - uses: actions/checkout@v4
      # Needed by sonar to get the git history for the branch the PR will be merged into.
      with:
        fetch-depth: 0
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        # formerly known as `service_account_key`
        credentials_json: '${{ secrets.GCP_TEST_KEY }}'
      env:
        GCP_TEST_KEY: '${{ secrets.GCP_TEST_KEY }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2.0.0'
      with:
        version: '>= 416.0.0'
        project_id: '${{ secrets.DEV_PROJECT_ID }}'
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.0.1
    - name: Cache dependencies
      uses: actions/cache@v2
      env:
        cache-name: cache-poetry-v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./orchestration/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      id: dependencies
      run: poetry install
      working-directory: ${{ github.workspace }}/orchestration
    - name: Enforce coding style guide
      run: poetry run autopep8 --recursive --diff --exit-code .
      working-directory: ${{ github.workspace }}/orchestration
      if: always() && steps.dependencies.outcome == 'success' # run all three checks, even if a prior check fails
    - name: Check static types
      run: poetry run mypy
      working-directory: ${{ github.workspace }}/orchestration
      if: always() && steps.dependencies.outcome == 'success' # run all three checks, even if a prior check fails
    - name: Run test suite
      run: poetry run pytest -v
      # for debugging.
      # run: poetry run pytest -v -k "ingress"
      working-directory: ${{ github.workspace }}/orchestration
      if: always() && steps.dependencies.outcome == 'success' # run all three checks, even if a prior check fails
